name: Java CI

on: [push, pull_request]

jobs:
  setup_Java:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Add Java to PATH
      run: |
        java_path=$(which java)
        java_dir=$(dirname "$java_path")
        echo "Java executable path: $java_path"
        echo "Java directory: $java_dir"
        ls -l $java_dir
        export PATH=$java_dir:$PATH
        echo $PATH

  whitebox_test_Mapper:
    needs: setup_Java
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: build
      run: |
        cd WordCount/WordCount
        javac -cp ".:Hadoop:JUnit/*" MapperTest.java
    
    - name: exec_test 
      run: |
        cd WordCount/WordCount
        java -cp ".:Hadoop:JUnit/*" org.junit.runner.JUnitCore MapperTest

  whitebox_test_Reduce:
    needs: setup_Java
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: build
      run: |
        cd WordCount/WordCount
        javac -cp ".:Hadoop:JUnit/*" ReducerTest.java 
    
    - name: exec_test 
      run: |
        cd WordCount/WordCount
        java -cp ".:Hadoop:JUnit/*" org.junit.runner.JUnitCore ReducerTest

  blackbox_test:
    needs: setup_Java
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: build
      run: |
        cd WordCount/WordCount
        javac -cp ".:Hadoop:JUnit/*" WordCountTest.java
    
    - name: exec_test 
      run: |
        cd WordCount/WordCount
        java -cp ".:Hadoop:JUnit/*" org.junit.runner.JUnitCore WordCountTest 

